#!/bin/bash

vagrant destroy -f
vagrant up

vagrant ssh -c "cd /vagrant/c_check; ./docker_build"
vagrant ssh -c "cd /vagrant/golang; ./docker_build"

vagrant ssh -c "cd /vagrant/c_check; ./docker_run"
vagrant ssh -c "cd /vagrant/golang; ./docker_run"
