#!/bin/bash

rsync -av runner runner_api shared_code_templates runner.codefluent.us:~

ssh runner.codefluent.us "cd runner_api; ./installer.sh"
ssh runner.codefluent.us "cd runner; ./installer.sh"
ssh runner.codefluent.us "cd runner/build_and_run; ./build_and_run_all; ./run_all_with_simple_report"
