#!/bin/bash

vagrant destroy -f
vagrant up

echo "building and running"
echo "note: we build and run so that changes can be made in the 'code' directory and the build process will update the image before running it again"
vagrant ssh -c "cd /vagrant/golang; ./docker_build; ./docker_run"
