#!/bin/bash

vagrant destroy
vagrant up
vagrant ssh -c "cd /vagrant; ./dockerize/dockerize"

# Now that docker is installed, run an Ubuntu container so that it pulls the
# Ubuntu repository, which can take a little while, so should also be
# automated.
vagrant ssh -c "sudo docker run ubuntu /bin/echo hello world"
