#!/bin/bash

cat >> /etc/apt/sources.list <<ENDOFFILE

deb http://ppa.launchpad.net/dotcloud/lxc-docker/ubuntu precise main 
deb-src http://ppa.launchpad.net/dotcloud/lxc-docker/ubuntu precise main 
ENDOFFILE
