#!/bin/bash

##############################################################################
# Set the locale
##############################################################################

# Set the locale
sudo locale-gen en_US.UTF-8

# Sometimes it fails, try again
sudo locale-gen en_US.UTF-8

sudo /usr/sbin/update-locale LANG=en_US.UTF-8

##############################################################################
# Update the packages on the system
##############################################################################

sudo apt-get -y update
sudo apt-get -y upgrade
