#!/bin/bash

tmux start-server
tmux new-session -d -s coderepoDevelopment -n initialWindow

tmux new-window -tcoderepoDevelopment:0 -n runner_api
tmux send-keys './runner_api/run_development_server.sh' 'C-m'

tmux new-window -tcoderepoDevelopment:1 -n website_run_nanoc_view
tmux send-keys './website/run_nanoc_view.sh' 'C-m'

tmux new-window -tcoderepoDevelopment:2 -n website_run_nanoc_compile
tmux send-keys 'cd ./website/; while (true); do ./update_code_templates.rb; nanoc; sleep 0.5; done' 'C-m'

tmux new-window -tcoderepoDevelopment:3 -n website_karma
tmux send-keys 'cd ./website/; karma start' 'C-m'

tmux new-window -tcoderepoDevelopment:4 -n kill_session
tmux send-keys 'tmux kill-session -t coderepoDevelopment'

tmux new-window -tcoderepoDevelopment:5 -n misc

tmux -2 attach-session -t coderepoDevelopment
