#!/bin/bash

tmux start-server
tmux new-session -d -s codefluentDevelopment -n initialWindow

tmux new-window -tcodefluentDevelopment:0 -n runner_api
tmux send-keys './runner_api/run_server.sh' 'C-m'

tmux new-window -tcodefluentDevelopment:1 -n website_run_nanoc_view
tmux send-keys './website/run_nanoc_view.sh' 'C-m'

tmux new-window -tcodefluentDevelopment:2 -n website_run_nanoc_compile
tmux send-keys 'cd ./website/; while (true); do nanoc; sleep 0.5; done' 'C-m'

tmux -2 attach-session -t codefluentDevelopment
