#!/bin/bash

source shared

for example_name in `ls ../code_templates`
do 
  runner_name=`cat ../code_templates/$example_name/Runner`
  run_in_runner "./docker_run /vagrant/code_templates/$example_name $runner_name"
done
