#!/bin/bash

source shared

example_name=$1

root_path=`runner_root_path`

runner_name=`cat ../../shared_code_templates/$example_name/Runner`
run_in_runner "./docker_run $root_path/shared_code_templates/$example_name $runner_name"
