#!/bin/bash

function run_in_runner {
  if [ -d /home/vagrant ]; then
    (
      cd /vagrant/runner
      myecho $1
      bash -c "$1"
    )
  elif [ -d /home/ubuntu ]; then
    (
      cd ~/runner
      myecho $1
      bash -c "$1"
    )
  fi
}

function runner_root_path {
  if [ -d /home/vagrant ]; then
    echo /vagrant
  else
    echo ~
  fi
}

function myecho {
  return 0
  #echo $1
}
