#!/bin/bash

# We update the shared_code_templates, too, so that we can run them to test
# that the updated runners are working correctly.

rsync -av --delete runner shared_code_templates runner.codefluent.us:~
ssh runner.codefluent.us "cd runner/build_and_run; ./build_and_run_all; ./run_all_with_simple_report"
