#!/bin/bash

path_to_mount_as_code=$1
runner_name=$2

(
  cd runner_containers/$runner_name
  sudo docker run -t --interactive=false -v $path_to_mount_as_code:/code:ro codefluent/$runner_name /bin/bash ./runner
)
